before:
  hooks:
    - go mod download
    - make ui
archives:
  - id: openvoxview
builds:
  - id: openvoxview
    ldflags: -s -w -X 'main.VERSION={{.Version}}' -X 'main.COMMIT={{.Commit}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
nfpms:
    - vendor: Vox Pupuli
      homepage: https://github.com/voxpupuli/openvoxview
      maintainer: Vox Pupuli <voxpupuli@groups.io>
      description: |-
          PuppetDB Dashboard
      license: Apache 2.0
      formats:
          - deb
          - rpm
release:
  github:
    owner: voxpupuli
    name: openvoxview
  name_template: "Release v{{.Version}}"
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
